enum NativeAuthLabels {
    static let accountSectionTitle = "账号"
    static let email = "邮箱"
    static let password = "密码"
    static let username = "用户名"
    static let nickname = "昵称（可选）"
    static let signIn = "登录"
    static let signUp = "注册"
    static let signInOrSignUp = "登录 / 注册"
    static let signOut = "退出登录"
    static let unsetNicknamePlaceholder = "未设置"
    static let emailTaken = "邮箱已被注册"
    static let usernameTaken = "用户名已被占用"
    static let invalidCredentials = "邮箱或密码错误"
    static let networkUnavailable = "网络不可用，请稍后重试"
    static let weakPassword = "密码至少 8 位"
    static let invalidEmail = "邮箱格式有误"
    static let invalidUsername = "用户名格式不合法"
    static let invalidNickname = "昵称格式不合法"
}
